### ISSUE TITLE
Blog series page doesnt render properly

### ISSUE THREAD

**Issue by jasonhimmelstein** [andrewconnell/accom-site-issues#3]
![blog series](https://user-images.githubusercontent.com/8984798/63045069-2f087a00-be95-11e9-802d-c89b993fb921.jpg)

**Comment by andrewconnell** [comment]
Ty... issue with two builds going at the same time and clobbering each other. Fixing builds to be more isolated.

**Comment by andrewconnell** [comment]
fixed... release collissions mitigated
