### ISSUE TITLE
Cloud tag "SharePoint Framework" returns no results

### ISSUE THREAD

**Issue by ruudsolidnl** [andrewconnell/accom-site-issues#5]
When I navigate to Url "https://www.andrewconnell.com/tags/SharePoint-Framework" I do not see any content. However, when I navigate to article at Url "https://www.andrewconnell.com/blog/sharepoint-framework-v1-8-0-what-s-in-the-latest-update-of-spfx" I do see this one is tagged with then value "SharePoint Framework".

**Comment by andrewconnell** [comment]
Good catch... this is really strange. It works fine locally, but not on the site or in my preview site. This is confusing... but something I'll get sorted.

EDIT: affecting all tags with spaces in the name

**Comment by ruudsolidnl** [comment]
Hi Andrew,

No worries, always something to learn 😊. Sorry I missed the Voitanos call; I’m in the middle of some release, so kinda madhouse at this point.

Best regards,
Ruud

Van: Andrew Connell <notifications@github.com>
Verzonden: donderdag 29 augustus 2019 17:14
Aan: andrewconnell/accom-site-issues <accom-site-issues@noreply.github.com>
CC: Ruud van Engelen <ruud@solidnl.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [andrewconnell/accom-site-issues] Cloud tag "SharePoint Framework" returns no results (#5)


Good catch... this is really strange. It works fine locally, but not on the site or in my preview site. This is confusing... but something I'll get sorted.

**Comment by andrewconnell** [comment]
No worries... the recording is up if you are curious when you free up.

Found the root cause of this issue and know how to fix it, but breaks something else so got a message into a forum seeking input before I move forward after I fought with this for too long last night :)

**Comment by andrewconnell** [comment]
fixed... thanks again!

**Comment by ruudsolidnl** [comment]
Nice one!

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Andrew Connell <notifications@github.com>
Verzonden: Saturday, August 31, 2019 12:32:50 PM
Aan: andrewconnell/accom-site-issues <accom-site-issues@noreply.github.com>
CC: Ruud van Engelen <ruud@solidnl.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [andrewconnell/accom-site-issues] Cloud tag "SharePoint Framework" returns no results (#5)


fixed... thanks again!
